INSERT INTO users ( HABITIDS, NUMBER_OF_HABITS, PASSWORD, USERID) VALUES
( array[1, 2, 0, 0, 0], 2, '$2a$12$IpjjxaqimxiRlOCpZVJQ..Y0RLfJMrBPhy3e8Xu3l3808SoDYF5Yi', 'sulthan'),
( array[0, 0, 0, 0, 0], 0, '$2a$12$IpjjxaqimxiRlOCpZVJQ..Y0RLfJMrBPhy3e8Xu3l3808SoDYF5Yi', 'jhon'),
( array[3, 4, 5, 0, 0], 3, '$2a$12$qmZgVgp.ygMBc79dy5c.euDL.IB7xzhow22p.rYp24LZnCVARvfSy', 'smith');

INSERT INTO habit (HABITID, CURR_DAY, DAYS, NAME, NUMBER_OF_DAYS, USERID)
VALUES
(1, 3, '[{"tasks":["sing"],"note":"sang","date":0},{"tasks":["sing"],"note":"sang","date":0},{"tasks":["sing"],"note":"sang","date":0},null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null]', 'singing', 30, 'sulthan'),
(2, 0, '[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null]', 'dancing', 120, 'sulthan'),
(3, 0, '[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null]', 'cooking', 50, 'smith'),
(4, 1, '[{"tasks":["code 1 hr"],"note":"done","date":0},null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null]', 'code', 100, 'smith'),
(5, 0, '[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null]', 'singing', 365, 'smith');
